### ISSUE TITLE
Feature Request: formatter for Vagrantfile

### ISSUE THREAD

**Issue by markfaine** [mastazi/VS-code-vagrantfile#3]
It's nice that it has syntax highlighting but what I really need is to be able to correct the formatting.  I tried Ruby formatters but apparently a Vagrantfile is not a proper ruby file.

**Comment by mastazi** [comment]
Hi @markfaine first of all I'm sorry for the extremely late reply - somehow I missed the notification and didn't realise that there was an issue open.

This plugin applies Ruby syntax highlighting to Vagrantfile and related filetypes (e.g. Vagrantfile.local). 

I'm not sure in which ways a Vagrantfile is not a "proper Ruby file", but most linters are configurable and you can set them up in such a way that some issues are ignored. Maybe that could help?

Anyway, I'm going to close this issue because I consider linting and code completion functionality out of scope for this small project, all I wanted this plugin to do was just syntax highlighting and unfortunately I don't have enough free time to add more complex functionality. Of course I'm happy for anyone to fork the repo or submit pull requests so that we can add more features!
